name: Cargo Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: gen-rs - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - nightly

    steps:
    - uses: actions/checkout@v3
    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - run: cargo build --verbose
    - run: cargo test --verbose
    - run: cargo doc --no-deps
    - run: rm -rf ./docs
    - run: echo "<meta http-equiv=\"refresh\" content=\"0; url=gen_rs/index.html\">" > target/doc/index.html
    - run: cp -r target/doc ./docs